In [19]:
import pandas as pd
df=pd.read_csv('/content/blood_pressure.csv')
df

     patient     sex agegrp  bp_before  bp_after
0          1    Male  30-45        143       153
1          2    Male  30-45        163       170
2          3    Male  30-45        153       168
3          4    Male  30-45        153       142
4          5    Male  30-45        146       141
..       ...     ...    ...        ...       ...
115      116  Female    60+        152       152
116      117  Female    60+        161       152
117      118  Female    60+        165       174
118      119  Female    60+        149       151
119      120  Female    60+        185       163

[120 rows x 5 columns]

In [18]:
df.head(5)

   patient   sex agegrp  bp_before  bp_after
0        1  Male  30-45        143       153
1        2  Male  30-45        163       170
2        3  Male  30-45        153       168
3        4  Male  30-45        153       142
4        5  Male  30-45        146       141

In [8]:
df.tail(5)

     patient     sex agegrp  bp_before  bp_after
115      116  Female    60+        152       152
116      117  Female    60+        161       152
117      118  Female    60+        165       174
118      119  Female    60+        149       151
119      120  Female    60+        185       163

In [11]:
df.shape

(120, 5)

In [20]:
df.bp_before.mean()

156.45

In [21]:
df.bp_before.mode()

0    142
1    162
Name: bp_before, dtype: int64

In [12]:
df.isnull().any()

patient      False
sex          False
agegrp       False
bp_before    False
bp_after     False
dtype: bool

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   patient    120 non-null    int64
 1   sex        120 non-null    object
 2   agegrp     120 non-null    object
 3   bp_before  120 non-null    int64
 4   bp_after   120 non-null    int64
dtypes: int64(3), object(2)
memory usage: 4.8+ KB

In [14]:
df.describe()

          patient   bp_before    bp_after
count  120.000000  120.000000  120.000000
mean    60.500000  156.450000  151.358333
std     34.785054   11.389845   14.177622
min      1.000000  138.000000  125.000000
25%     30.750000  147.000000  140.750000
50%     60.500000  154.500000  149.500000
75%     90.250000  164.000000  161.000000
max    120.000000  185.000000  185.000000

In [17]:
df.loc[4]

patient          5
sex           Male
agegrp       30-45
bp_before      146
bp_after       141
Name: 4, dtype: object